### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by deimosfr** [vvanholl/elasticsearch-prometheus-exporter#101]
Hi,

Thanks for your hard work (it reminds me something :p). Do you plan to make a docker version of your exporter ?

By the way, thanks for the Grafana dashboard as well.

Thanks

**Comment by deimosfr** [comment]
Oops, just seen it's an Elasticsearch plugin. Don't you plan to make a specific exporter ?

**Comment by vvanholl** [comment]
Hi @deimosfr,

Thank you first for using my plugin :)

I developed it mainly to use as an ES plugin, not a standalone program.In fact I originally wanted to avoid using a third party component between ES and Prometheus.

It wouldn't be easy to transform as a single program. There are too many internal relations with ES components. The only and best way to do it is creating a coordinating node (not data and not master) with the plugin installed.

**Comment by lukas-vlcek** [comment]
@deimosfr You are probably looking for Prometheus exporter for Elasticsearch. Some exporters are listed here: https://prometheus.io/docs/instrumenting/exporters/

In some cases you want to be able to pull metrics from individual nodes as opposed from central proxy (exporter). For example if some nodes are disconnected from ES cluster then you will not get their metrics using exporter. But if you instruct Prometheus correctly it will be able to scrape metrics even from nodes that are not part of the cluster.

@vvanholl I suggest closing this ticket.

**Comment by deimosfr** [comment]
Totally agree @lukas-vlcek thanks
