### ISSUE TITLE
6.2.4 405 error

### ISSUE THREAD

**Issue by diaosichen** [vvanholl/elasticsearch-prometheus-exporter#105]
when i start the exporter. the error happen like this:
{"error":"Incorrect HTTP method for uri [/_prometheus/metrics] and method [GET], allowed: [POST]","status":405}

elasticsearch version:6.2.4
How cant i set it ?thanks!

**Comment by HaveFun83** [comment]
What do you set in your uri: value?
```
uri: http://$elk-service.$namespace.svc.cluster.local:9200
```
Maybe you missed the http:// in front?

**Comment by cnolden** [comment]
I experienced this error when not all nodes in the cluster had the plugin installed. Installing the plugin on all nodes fixed the issue for me (version 6.2.4)
