### ISSUE TITLE
What about 5.0 version?

### ISSUE THREAD

**Issue by mcortinas** [vvanholl/elasticsearch-prometheus-exporter#11]
Hello,

 ES 5.0 was delivered last monday... Do you know when it will be compatible with 5.0??

Marc

**Comment by bobymicroby** [comment]
@mcortinas Check out #12  . 

You can test if it is working by

1. Build and create the plugin zip
``` mvn assembly:assembly ```

2. Upload to ES 
``` scp  target/releases/elasticsearch-prometheus-exporter-1.0-SNAPSHOT.zip root@your.server:/root  ```

3. Install 
``` /usr/share/elasticsearch/bin/elasticsearch-plugin install -b file:///root/elasticsearch-prometheus-exporter-1.0-SNAPSHOT.zip ```


Please write if you find any issues.

**Comment by vvanholl** [comment]
Hi all,

Version 5.0.0.0 has been released today with #12 

Vincent

**Comment by mcortinas** [comment]
thank you so much!
