### ISSUE TITLE
Increment metric indices fails for 5.2.1.0

### ISSUE THREAD

**Issue by grantstephens** [vvanholl/elasticsearch-prometheus-exporter#111]
Hi. I'm running exporter version 5.2.1.0 and the logs are fill of `Cannot increment metric xxx` for the following metrics:
```
indices_fielddata_evictions_count
indices_requestcache_hit_count
indices_requestcache_miss_count
indices_querycache_cache_count
indices_querycache_evictions_count
indices_querycache_hit_count
```
I see there was a similar issue for version 2- were the changes not applied in v5?

**Comment by daachi** [comment]
Seeing this in 5.3 as well
