### ISSUE TITLE
Export ES and JVM Version as labels

### ISSUE THREAD

**Issue by mjtrangoni** [vvanholl/elasticsearch-prometheus-exporter#113]
Hi @vvanholl ,

As a Feature Request, it would be nice to have  the ES and JVM Version exported as labels.

```
java -version 2>&1 | grep openjdk
openjdk version "1.8.0_171"
```

Is that possible? Maybe at this metric here,
```
es_cluster_status{cluster="es-mon",} 0.0
```
to something like,
```
es_cluster_status{cluster="es-mon",version="6.3.1",jvm="1.8.0_171"} 0.0
```

Thanks!

**Comment by lazyusername** [comment]
I am not sure about the metric `es_cluster_status` but it would be definitely useful to have ES version in a label somewhere.
