### ISSUE TITLE
Export metrics to /metrics

### ISSUE THREAD

**Issue by yehaolan** [vvanholl/elasticsearch-prometheus-exporter#114]
Since the Prometheus that I have will scrape in the path `/metrics`, I would like to export prometheus metrics to `/metrics` instead of `/_prometheus.metrics`. How can I build the source code with new path specified?

**Comment by wfindley** [comment]
you can't do this.  elasticsearch has its *own* endpoint that serves on `/metrics`

**Comment by lukas-vlcek** [comment]
You can configure Prometheus to scrape from non-default path by setting:
```
metrics_path: /_prometheus/metrics
```
See <https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config>

**Comment by IronManZ** [comment]
I would like to see the path '/_prometheus.metrics' to be configurable. The existing infrastructure in my company use fixed path such as `/monitor/metrics`, and they cannot change it.

**Comment by yehaolan** [comment]
Configurable path is good. Since currently is not configurable, deploying Nginx to redirect `/metrics` . to `/_prometheus.metrics` might be a good option for you so far. @IronManZ
