### ISSUE TITLE
es_index_* metrics are not exported anymore

### ISSUE THREAD

**Issue by jperville** [vvanholl/elasticsearch-prometheus-exporter#115]
Until recently, we were running ElasticSearch v5.5.1 with version 5.5.1.0 of this plugin. We were using the `es_index_*` metrics in our Grafana dashboards for example to list the number of documents stored in each index with the `es_index_doc_number` metric.

After upgrading to ElasticSearch v6.2.1 and this plugin to version 6.2.1.0,  the `es_index_*` metrics are not exported anymore and our Grafana dashboards are less useful.

Apparently, the `es_index_*` metrics were removed in #70 and especially in https://github.com/vvanholl/elasticsearch-prometheus-exporter/commit/775b2268c02c47b99247ec816d89b099ab27d7fc#diff-d03a301dd08e2be945563f2a77dc90b7L631 and below.

Is there any possibility to get those metrics back in a future version of this exporter?

**Comment by lukas-vlcek** [comment]
You are right, it got lost here:
https://github.com/vvanholl/elasticsearch-prometheus-exporter/commit/775b2268c02c47b99247ec816d89b099ab27d7fc#diff-d03a301dd08e2be945563f2a77dc90b7L878

I think this can be my fault as well. I am going to fix this.

**Comment by lukas-vlcek** [comment]
Once we merge https://github.com/vvanholl/elasticsearch-prometheus-exporter/pull/128 into master I will add tests for per index metrics too so this will not happen again in the future 😄
