### ISSUE TITLE
Elasticsearch v6.4.2 is now available

### ISSUE THREAD

**Issue by nikolay** [vvanholl/elasticsearch-prometheus-exporter#126]
@vvanholl Thank you in advance!

**Comment by nikolay** [comment]
This is an Elastic stack limitation as far as I know. I'm not sure why such a shortsighted decision was made by Elastic to require a patch-level match of the version. So, if you use ten plugins, let's say, you will have to wait months to apply a security update as typical plugin authors don't bother to update immediately after releases.

At this point, I'm starting to fork all Kibana and Elasticseach plugins I use, and I have my build process, and I don't rely on the makefiles of these plugins or their release artifacts. This is currently the only path to freedom, flexibility, and be able to react immediately to security releases from the Elastic stack.

Imagine there's a huge security flaw discovered in 6.4.1, and you need to upgrade to 6.4.2 immediately. I typically ping on various channels the plugin authors, and I use a total of just three plugins. I feel sorry for those using more!

**Comment by vvanholl** [comment]
Hi, Version 6.4.2.0 has just been release !

By the way, it is currently impossible to publish a plugin release that works for a set of ES versions, since the plugin has a parameter in plugin-descriptor.properties called elasticsearch.version that must be the same as ES otherwise the plugin can not install.

**Comment by nikolay** [comment]
@vvanholl How about the crazy idea to generate 5 patch versions in advance then? Let's say, when 6.4.0 got released, you'd publish 6.4.0 to 6.4.5. 😄

**Comment by cgoeller** [comment]
Thanks for the release. 👍 

If Elastic integrated the functionality into ES, it would be even easier ...
