### ISSUE TITLE
Elastic 6.5.0 is available

### ISSUE THREAD

**Issue by nikolay** [vvanholl/elasticsearch-prometheus-exporter#134]
@vvanholl Please, release a compatible version. Thanks!

**Comment by lukas-vlcek** [comment]
I do not think I can cut new releases.

**Comment by vvanholl** [comment]
Hi @nikolay, I took a first look at this new ES version and tried a build without success.
In fact there are many changes in the code so I must deal with that and a new release could take more time as usual.

**Comment by nikolay** [comment]
@vvanholl I had the same suspicion. Thank you for all your great work!

**Comment by lukas-vlcek** [comment]
BTW, @nikolay I think you should consider starting branches for all releases. This will simplify process of back-porting future changes back to older releases. WDYT?

For example, I am currently working on https://github.com/vvanholl/elasticsearch-prometheus-exporter/issues/124 and I am about to send PR soon. But, if I my code will not be compatible with both the 6.4.x and 6.5.x ES releases then I do not know how we can easily back-port features like that to older releases.

**Comment by nikolay** [comment]
@lukas-vlcek Our code already works with 6.5.0 but I need your plugin plus the Kibana exporter plugin - I always have to wait for the plugins to upgrade.

**Comment by vvanholl** [comment]
I am currently working on porting the plugin to 6.5.0. The tests are OK and the plugin seems working well, but I have to continue checking everything is fine.

**Comment by lukas-vlcek** [comment]
@vvanholl Feel free to ping me if you feel like someone else should review the code before releasing (just create PR).

BTW, what do you think about starting branches for new version releases? Do you think we will be able doing good going forward with just single 5.x branch. Will it allow us doing back-ports for releases pre 5.6.x and after 5.6.x?

**Comment by lukas-vlcek** [comment]
It is out now: https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/tag/6.5.0.0

**Comment by nikolay** [comment]
Thank you, @vvanholl and @lukas-vlcek!
