### ISSUE TITLE
Remove coverage badge from README

### ISSUE THREAD

**Issue by lukas-vlcek** [vvanholl/elasticsearch-prometheus-exporter#135]
Gitlab badges were added in 3eb795d1f17 but we should remove the one for coverage. According to Elasticsearch documentation for [test-coverage-analysis](
https://github.com/elastic/elasticsearch/blob/master/TESTING.asciidoc#test-coverage-analysis) it is currently not supported.

**Comment by vvanholl** [comment]
No problem, can you make a PR for that ?
