### ISSUE TITLE
Remove parenthesis from integration test names

### ISSUE THREAD

**Issue by lukas-vlcek** [vvanholl/elasticsearch-prometheus-exporter#137]
As reported here https://github.com/elastic/elasticsearch/issues/35692 there can be issues when running individual integration tests that contain parenthesis in its name.

This means we need to modify all affected *.yml files in `rest-api-spec/test` folder.

**Comment by lukas-vlcek** [comment]
@nik9000 Do you know if the fix will be available for both the ES 5.x and 6.x?

**Comment by nik9000** [comment]
Not in 5.x, no.

**Comment by lukas-vlcek** [comment]
@nik9000 Ok, well, then I will need to remove parenthesis anyway (I will be back-porting all esplugin tests back to ES 5.x as much as possible). But hey, thanks a lot Nik!

**Comment by lukas-vlcek** [comment]
Verified, parenthesis are not breaking individual integration tests for ES 7.x any longer (`master` branch as of writing).

Running tests like the following is ok:
```
gradle integTest \
  -Dtests.class=org.elasticsearch.rest.PrometheusRestHandlerClientYamlTestSuiteIT \
  -Dtests.method="test {yaml=resthandler/30_00_index_level_info/Index level statistics (general)}"
```
Based on @nik9000 comment above this should be also fixed for ES 6.x.
Closing as WONTFIX for now.
