### ISSUE TITLE
Expose whole cluster logs

### ISSUE THREAD

**Issue by kayrus** [vvanholl/elasticsearch-prometheus-exporter#14]
I'd like to monitor data and master nodes JVM logs, but nor data neither master have enabled 9200 HTTP port. Only client pods have it. And metrics of the client show only client related metrics. Is it possible to server whole cluster metrics without enabling HTTP port on data and master nodes? Kopf plugin already provide this info.

Does it sound reasonable to implement this feature?

**Comment by lukas-vlcek** [comment]
Does Kopf provide node logs? (I do not think so but I might be wrong...)
As far as getting metrics for all nodes in the cluster via hitting a single node that is not supported in this plugin but I think it should be possible to implement.
