### ISSUE TITLE
Elastic issue 5.6.4

### ISSUE THREAD

**Issue by IbaiAlonso** [vvanholl/elasticsearch-prometheus-exporter#141]
Hi,

I had this plugin setup in both PROD (5.6.4) and DEV (6.4.2). In dev is working fine. However in PROD all the clusters (Cross Cluster Search enabled) got unestable status due to the plugin (before installing it never happened)

Basically, the servers ran out of resources and the cluster degraded eventually. I would say that the perfomance was ok 6 hours.

**Comment by lukas-vlcek** [comment]
Can you share the logs from ES nodes please?
If the cluster was running ok for 6hrs do you have any collected metrics in Prometheus that you could share as well (sharing at least screenshots of Prometheus UI would be good start).
