### ISSUE TITLE
Add metrics on exceptions

### ISSUE THREAD

**Issue by johnskopis** [vvanholl/elasticsearch-prometheus-exporter#147]
Related to #19 

prometheus client_java includes a simple logger: https://github.com/prometheus/client_java#logging

When prometheus-exporter plugin registers it can hook into LogManager context and setup a Logger that counts exceptions.

This is useful because Elasticsearch seems to log lots of IllegalArgumentException. Look at MapperService.java for example. This is likely the case elsewhere but I haven't checked. These exceptions result in the ES api returning a 400 error to client. The exceptions themselves are buried at DEBUG level (o.e.a.a.i.m.p.TransportPutMappingAction).

My thinking is that adding exception counters could be useful by annotating exceptions in es, e.g. IllegalArgumentException caused by MapperServiceTotalFieldsExceeded (or just subclass), and capturing inside prometheus exporter logger. I envision metrics like:

es_exceptions{ex="illegal_argument_exception", caused_by="MapperServiceTotalFieldsExceeded} 1

Does this make sense?

Is there a better way to do this? Is this already exposed somewhere?

Thanks,
John

**Comment by lukas-vlcek** [comment]
Sounds like interesting idea to me.

> When prometheus-exporter plugin registers it can hook into LogManager context and setup a Logger that counts exceptions.

Are there any code examples of what "it can hook into LogManager context" means? If I understand correctly we would need to implement this directly by calling the Java API of Prometheus Java client.

**Comment by johnskopis** [comment]
see "Programmatically Modifying the Current Configuration after Initialization" at https://logging.apache.org/log4j/2.x/manual/customconfig.html

Looks like there's a utility:
https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/common/logging/Loggers.java#L134-L145

ex:
https://github.com/elastic/elasticsearch/blob/master/plugins/transport-nio/src/test/java/org/elasticsearch/transport/nio/NioTransportLoggingIT.java#L38-L43

Maybe we should ask Elastic if they think it's a good idea. If so, maybe they will add synchronization and develop some kind of logging plugin interface...seems like the intended use was for tests only :)

If you look at what the InstrumentedAppender does it's pretty simple:
https://github.com/prometheus/client_java/blob/master/simpleclient_log4j2/src/main/java/io/prometheus/client/log4j2/InstrumentedAppender.java

Either subclass that or just use as a reference. the appender takes a LogEvent that should have info about the exception:
https://logging.apache.org/log4j/2.0/log4j-core/apidocs/org/apache/logging/log4j/core/LogEvent.html

I was just thinking it might make sense to make an appender for each class that surfaces this error (index, search, etc) so you have:

search_es_exceptions{ex="?", caused_by="?"} 
index_es_exceptions{ex="?", caused_by="?"} 
...

Maybe we should open an upstream issue? Seems like there's already a metrics facility in elasticsearch but these illegal_argument_exception are not instrumented.

**Comment by lukas-vlcek** [comment]
I will dig deeper into this. One thing that would be very interesting is having exception metric on index shard allocation failures IMO.

**Comment by richm** [comment]
Is there a way to get an access log like the apache access log?  Something that lists - incoming IP; URL requested; result code

The last one is really important - it would be nice to export statistics like number of 400 response codes, number of 401, number of 403, number of 404, number of 429, etc. etc.
