### ISSUE TITLE
Many 5.x release tags are not attached to commits used to build final upstream artifacts

### ISSUE THREAD

**Issue by lukas-vlcek** [vvanholl/elasticsearch-prometheus-exporter#152]
The following releases are using incorrect gradle:build-tools version and plugin version:
- `5.6.13.0`: [`gradle.properties`](https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/5.6.13.0/gradle.properties#L3), [`build.gradle`](https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/5.6.13.0/build.gradle#L11)
- `5.6.13.1`: [`gradle.properties`](https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/5.6.13.1/gradle.properties#L3), [`build.gradle`](https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/5.6.13.1/build.gradle#L11)
- `5.6.14.0`: [`gradle.properties`](https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/5.6.14.0/gradle.properties#L3), [`build.gradle`](https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/5.6.14.0/build.gradle#L11)

This is causing the `gradle check` to use different version of ES and it installs different version of Prometheus plugin into it as well.

**Comment by lukas-vlcek** [comment]
To be hones I do not understand how it is even possible that those versions of plugins (when downloaded from `https://distfiles.compuscene.net/elasticsearch/elasticsearch-prometheus-exporter-5.6...`) actually work in ES. It seem that the plugin-descriptor.properties file magically contains correct version when downloaded from that resource.

**Comment by lukas-vlcek** [comment]
There seem to be additional version mismatches here:

- `5.6.12.0`: [`gradle.properties`](https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/5.6.12.0/gradle.properties#L3)
- `5.6.11.0`: [`gradle.properties`](https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/5.6.11.0/gradle.properties#L3)
- `5.6.10.0`: [`gradle.properties`](https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/5.6.10.0/gradle.properties#L3)
- `5.6.9.1`: [`gradle.properties`](https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/5.6.9.1/gradle.properties#L3)
- `5.6.9.0`: [`gradle.properties`](https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/5.6.9.0/gradle.properties#L3)
- `5.6.8.0`: [`gradle.properties`](https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/5.6.8.0/gradle.properties#L3)
- `5.6.7.0`: [`gradle.properties`](https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/5.6.7.0/gradle.properties#L3)
- `5.6.6.0`: [`gradle.properties`](https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/5.6.6.0/gradle.properties#L3)
- `5.6.5.0`: [`gradle.properties`](https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/5.6.5.0/gradle.properties#L3)

The rest of `5.6.x` tags seem to be ok (that is `5.6.4.0`, `5.6.3.0`, `5.6.2.0`, `5.6.1.0` and `5.6.0.0`).
Also the rest of tags back to `5.4.2.0` seem to be ok as well (in fact it goes back to c5754a4 where the project switched to gradle).

And I think the issue started when the branch `5.x` was spin off from the `master`. The issue seems to be that all mismatching `5.x` tags are attached to commits in the master branch (which is in fact pointing to ES 6.x version).

This means that building some of the above mentioned 5.x releases from relevant git tag does not yield the same artifact that can be downloaded from <https://distfiles.compuscene.net/elasticsearch/> URL. Instead it seems that 5.x releases were built from `5.x` branch but those commits do not share any relevant tag (one can only guess from the commit message?).

I see two problems here:

- It is confusing: It does not clearly document which functionality is included in particular 5.x plugin release. For example, looking at the commits in [`5.6.13.0` tag view](https://github.com/vvanholl/elasticsearch-prometheus-exporter/commits/5.6.13.0) it seems that [index level metrics](https://github.com/vvanholl/elasticsearch-prometheus-exporter/pull/131/commits/0610f6734f1e4f73209307c80d0f519e7c7fe6c4) are included. But they are not.

- Reproducibility and security concerns:  It is not clear from which commit the final 5.x artifacts were built.

Apart from this there is relation to #139 because the [script I developed to automatically create release branches](https://github.com/vvanholl/elasticsearch-prometheus-exporter/issues/139#issuecomment-443795806) in the new versioning model can not be directly used and needs more work.

**Comment by lukas-vlcek** [comment]
@vvanholl Actually, we should be able to move mismatching 5.x tags to correct commits in 5.x branch, is that correct? That will address both the problems above and also will make the script for branching working correctly again. WDYT?

**Comment by richm** [comment]
It is usually a very bad idea to move and re-publish tags which have already been published.  But in this case, it might be justified.

**Comment by lukas-vlcek** [comment]
@richm Exactly.

**Comment by lukas-vlcek** [comment]
I've been reading about `git tag` in man and there is [discussion section on re-tagging](https://git-scm.com/docs/git-tag#_on_re_tagging). I suggest to follow the _sane thing_ approach; ie. 1) add few new tags, 2) document the issue for users.

For example there is tag `5.6.13.1` which is pointing to commit in master branch (which is not correct because it is ES 6.x code) so we create a **new tag `5.6.13.2`** as if it were a new release, attach it to correct commit in `5.6.13` branch (*), keep `5.6.13.1` tag where it is today and document for users that they should never build from that tag anymore.

(*) Before we do that we will need to migrate to new branching model because `5.6.13.2` tag will actually need a new commit and I do not think it would be good idea to have that commit in existing `5.x` branch. I would rather see that commit in new `5.6.13` branch (see #139).

When migrating to the new branching model we will ignore mismatched tags. This will need some handling in my migration script but I think that is doable.

I am going to do this all under my fork at [lukas-vlcek/elasticsearch-prometheus-exporter](https://github.com/lukas-vlcek/elasticsearch-prometheus-exporter). This will make it easy to create PR against @vvanholl repo in the future.
