### ISSUE TITLE
Possible to dynamically update the prometheus.indices setting

### ISSUE THREAD

**Issue by accorvin** [vvanholl/elasticsearch-prometheus-exporter#159]
Per the documentation for this plugin, I'd like to disable fetching per-index settings by setting `prometheus.indices: false`.

Is it possible to adjust this setting without requiring a restart of the Elasticsearch nodes?

**Comment by lukas-vlcek** [comment]
Not at this moment, but I was looking into the code and it should be doable to make all `prometheus.*` settings [dynamic](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/cluster-update-settings.html). I think this can be useful feature. I am working on PR.
