### ISSUE TITLE
6.6.2 support

### ISSUE THREAD

**Issue by davidkarlsen** [vvanholl/elasticsearch-prometheus-exporter#167]
Support ES 6.6.2

**Comment by vvanholl** [comment]
PR https://github.com/vvanholl/elasticsearch-prometheus-exporter/pull/168 has just been opened for this purpose

**Comment by lukas-vlcek** [comment]
https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/tag/6.6.2.0
I think we can close this one, right?
