### ISSUE TITLE
slow reporting of metrics

### ISSUE THREAD

**Issue by davidkarlsen** [vvanholl/elasticsearch-prometheus-exporter#172]
Our datanodes use quite a lot of time to report the metrics:
```
et2448@ilp-aot-elk04 ~]$ time curl localhost:9202/_prometheus/metrics -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23.1M  100 23.1M    0     0  1099k      0  0:00:21  0:00:21 --:--:-- 5270k

real    0m21.530s
user    0m0.010s
sys     0m0.021s
[et2448@ilp-aot-elk04 ~]$ 
```
can something be done to speed this up? They have a fair amount of indexes though.

**Comment by lukas-vlcek** [comment]
That is 21 seconds?
Which version of plugin?

There are couple of calls done internally and they are done in sequential order - the second call is initiated only after the first one is finished, etc... we could speed things up by running all calls in parallel, but that could put more load on the server and it might not help much if one of the calls take 90% of total time. This might be the case of getting stats for all indices.

I would say we need to check how long individual calls take and then optimise the most expensive one. May be you can try to turn on slow search log (set threshold to 10 sec) and see if it caches the indices stats request (although I am not sure if slow search log catches also admin APIs). This will help us identify the call the we need to optimise first (I will check if we can filter out some data from indices stats response, this could help).

**Comment by davidkarlsen** [comment]
@sastorsl can you fill in the details?
