### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by kchaitu4** [vvanholl/elasticsearch-prometheus-exporter#181]
The exporter suddenly stopped working and I do not see any errors in the ELK Logs. I am able to curl to my ELK servers with the below url, but doesn't scrape any values. 

Please advice how to fix...Even Grafana has stopped loading the data.

**Comment by lukas-vlcek** [comment]
Which version of Elasticsearch and Prometheus plugin?
What happens when you curl the `_prometheus/metrics` endpoint? Does it timeout or do you get any error code? Can you see anything in Elasticsearch log at that time?
Last but not least, how many indices does your cluster have?

**Comment by kchaitu4** [comment]
Version is 6.5.4.0
when I run https://<url>_prometheus/metrics I get page cannot be reached.
Last reference about this plugin was... when ELK got restarted (manually) a couple of days back, but it stopped working just few hours before.
Currently we have only 38 indices.

**Comment by lukas-vlcek** [comment]
Are you able to list installed plugins in ES cluster? For example you can use [_cat/plugins](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/cat-plugins.html) like:
```
curl https://<url>/_cat/plugins?v
```

**Comment by kchaitu4** [comment]
i get authorization required message. I think this is expected.

**Comment by lukas-vlcek** [comment]
Yes, that is expected if ES runs on https. But you can pass credentials to curl.
If you can verify which plugins are installed in ES at this moment then this would be great. If not then it might be very hard to help you with this issue.

**Comment by kchaitu4** [comment]
i get {"statusCode":404,"error":"Not Found","message":"Not Found"}

**Comment by kchaitu4** [comment]
I found the issue....Its a human error. In Prometheus config the port was removed by my teammate assuming it was a different server. 

I am So Very sorry for bothering you.
Thanks for your time.

**Comment by lukas-vlcek** [comment]
You are welcome.
