### ISSUE TITLE
Elastic v6.7.2 is now available

### ISSUE THREAD

**Issue by davidkarlsen** [vvanholl/elasticsearch-prometheus-exporter#184]

**Comment by lukas-vlcek** [comment]
Please, @vvanholl can you remove your release https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/tag/6.7.2.0 and do it really against 6.x branch commits and stop doing it against master branch that has been upgraded to ES 7.x

Sorry for strong words but I will not be able to participate in this if you keep doing releases on wrong commits.

**Comment by vvanholl** [comment]
You are right. I have forgotten this bug that miss releases and tags againt master branch

So I have removed this release

I have to fix that also !

Sorry for the inconvenience :(

**Comment by lukas-vlcek** [comment]
Also remove the tag and force push it again. I think it is ok in this case to change (for once) public history of git repo.

**Comment by vvanholl** [comment]
Release and tags have been both removed from GitHub.

**Comment by vvanholl** [comment]
I am trying now to fix that

**Comment by vvanholl** [comment]
6.7.2.0 has been released. @lukas-vlcek can you check this is OK now ?

**Comment by vvanholl** [comment]
To resume my last actions
- Old Jenkins release process has been removed
- I do not longer push artifacts in a private repository
- I fixed the issue when releasing from another branch than master
- Releasing is now part of the GitLab pipeline
- There's now no hidden part, all is described in the repository (except my tokens)
