### ISSUE TITLE
Elastic v6.8.0 and v7.1.0 are now available

### ISSUE THREAD

**Issue by nikolay** [vvanholl/elasticsearch-prometheus-exporter#189]
@vvanholl and @lukas-vlcek Please, release compatible artifacts! Thanks in advance!

**Comment by lukas-vlcek** [comment]
For ES 7.1.0 support, see #190

**Comment by nikolay** [comment]
@lukas-vlcek Please, consider my request to have your own releases!

**Comment by vvanholl** [comment]
@nikolay @lukas-vlcek Please understand sometimes I am not very active on the repository flife since I do it on my spare time.

**Comment by nikolay** [comment]
I understand totally. Then you should delegate some of the work to @lukas-vlcek, who has earned his reputation in here already!

**Comment by lukas-vlcek** [comment]
@nikolay I think we should try to bring more long term contributors here instead. Every important commit needs review from at least 1 [CODEOWNER](https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/master/.github/CODEOWNERS) (depending on how @vvanholl sets this up, but I think 1 review from this list is the minimum). And given that ATM there are just two of them then if I do the commit then Vincent needs to approve and vice versa.

**Comment by vvanholl** [comment]
@lukas-vlcek I am agree. We always need someone who review the code from another contributor. 

This ensures the code to reach a better quality.

And of course contributors are welcome ! :)

**Comment by lukas-vlcek** [comment]
Releases are available here: [6.8.0.0](https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/tag/6.8.0.0), [7.1.0.0](https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/tag/7.1.0.0).  🎉
