### ISSUE TITLE
Can not increment metric indices_segments_number with value [negative], skipping

### ISSUE THREAD

**Issue by knweiss** [vvanholl/elasticsearch-prometheus-exporter#2]
Hi,

today I've noticed log entries like this in my elasticsearch log:

```
Aug 23 09:30:27 XXXX elasticsearch[27249]: [2016-08-23 09:30:27,085][ERROR][RestPrometheusMetricsAction]\
Can not increment metric indices_segments_number with value -19.000000, skipping
```

I took a look at the Prometheus metrics and found metric `es_indices_segments_number` (prefix "**es_**") of type Counter - which is only allowed to **increment**:

```
# HELP es_indices_segments_number Current number of segments
# TYPE es_indices_segments_number counter
```

Should the metric type be changed from Counter to Gauge?

**Comment by vvanholl** [comment]
Hi @knweiss, I have also noticed it today.

I am working on it.

**Comment by vvanholl** [comment]
This should be solved in release 2.3.5.3
https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/tag/2.3.5.3

**Comment by knweiss** [comment]
I've just deployed the new version and will keep an eye on it. Thanks a lot!

**Comment by knweiss** [comment]
The original metric seems to work now.

However, I get the same error message with two other metrics now:
```
Aug 24 12:31:04 XXXX elasticsearch[17967]: [2016-08-24 12:31:04,784][ERROR]\
[RestPrometheusMetricsAction] Can not increment metric jvm_classes_loaded_count with value -25.000000, skipping
Aug 24 12:31:04 XXXX elasticsearch[17967]: [2016-08-24 12:31:04,784][ERROR]\
[RestPrometheusMetricsAction] Can not increment metric indices_doc_deleted_count with value -1.000000, skipping
```

**Comment by vvanholl** [comment]
I have released version 2.3.5.4

**Comment by knweiss** [comment]
Thanks. I'll test it.

**Comment by knweiss** [comment]
Two early comments:

1. The release zip for version 2.3.5.4 is missing in the GitHub release tab listing (although it exists).
2. Three of the renamed metrics (`es_indices_doc_count`, `es_indices_doc_deleted_count`, and  `es_indices_querycache_miss_count`) are referenced in the current release `elasticsearch_rev2.json` [Elasticsearch Grafana dashboard](https://grafana.net/dashboards/266).

**Comment by vvanholl** [comment]
Hi,

1. Sorry for my error :(, It's fixed :)
2. The Grafana dashboard has been updated : https://grafana.net/dashboards/266/revisions

**Comment by knweiss** [comment]
Thank you!

Unfortunately, I found another metric with the wrong type: `indices_merges_total_auto_throttle_bytes`:

```
Aug 26 02:00:04 XXXX elasticsearch[28485]: [2016-08-26 02:00:04,769][ERROR]\
[RestPrometheusMetricsAction] Can not increment metric indices_merges_total_auto_throttle_bytes with value -1906502.000000, skipping
```

**Comment by vvanholl** [comment]
Hi,

I have just released version 2.3.5.5

**Comment by knweiss** [comment]
Okay, this version looks good so far: No new metric errors since yesterday. Thanks!

**Comment by knweiss** [comment]
Unfortunately, I found some more:

```
indices_flush_total_count
indices_flush_total_time_seconds
indices_indexing_index_count
indices_indexing_index_failed_count
indices_indexing_index_time_seconds
indices_merges_total_docs_count
indices_merges_total_number
indices_merges_total_size_bytes
indices_merges_total_time_seconds
indices_querycache_cache_count
indices_querycache_evictions_count
indices_querycache_hit_count
indices_refresh_total_count
indices_refresh_total_time_seconds
indices_search_fetch_count
indices_search_fetch_time_seconds
indices_search_query_count
indices_search_query_time_seconds
```

FWIW: Another option would be to use [UNTYPED Prometheus metrics](https://prometheus.io/docs/instrumenting/writing_exporters/#types):

> Often it won’t be obvious what the type of a metric is (especially if you’re automatically processing a set of metrics), use UNTYPED in that case. In general UNTYPED is a safe default.

**Comment by vvanholl** [comment]
Hi, Thank you for your advice :)

It's sometimes hard to guess from ElasticSearch if an internal metric is a counter or not, and you can't rely on it's name. In fact, for each metric, I should closely read the ES documentation to know what a metric is supposed to represent.

Maybe UNTYPED could solve this problem, but it could break Prometheus best practices. I have to think about it before.

**Comment by knweiss** [comment]
Check out e.g. the Prometheus `node_exporter`. It uses lots of untyped metrics for this reason.

**Comment by ricard0ff** [comment]
hey so after seeing this thread and using version  3.5.5 I'm also getting:

`[ERROR][RestPrometheusMetricsAction] Can not increment metric indices_querycache_hit_count with value -11.000000, skipping`

using elasticsearch-prometheus-exporter-2.3.5.5.zip

**Comment by vvanholl** [comment]
@knweiss : unfortunately the Java client for Prometheus (https://github.com/prometheus/client_java) seems to not manage UNTYPED.

I'm thinking about migrating all counters to gauge, but before I have to see if Prometheus supports changing a metric from counter to gauge.

**Comment by zazab** [comment]
Hi
any progress on this issue?

I'm getting lots of such errors on metrics `indices_querycache_evictions_count` and `indices_percolate_queries_count` (plugin version 2.4.4.0, elastic 2.4.4)
