### ISSUE TITLE
when using basic auth, what is the min role/permissions needed?

### ISSUE THREAD

**Issue by donbowman** [vvanholl/elasticsearch-prometheus-exporter#204]
its not obvious how to use this w/ basic auth with a minimum set of permissions.

**Comment by lukas-vlcek** [comment]
This Prometheus plugin is orthogonal to authentication/authorization. It basically adds a new REST endpoint to Elasticsearch HTTP API and access to this endpoint is controlled by security system used for Elasticsearch.
So for example you can use [SearchGuard](https://search-guard.com/) to setup and control access to ES REST endpoints. Or you can setup external proxy to control access to ES.
I do not know from the top of my head if this plugin will work correctly with X-Pack.

Which one do you use?

**Comment by donbowman** [comment]
i am using w/ the new [cloud-on-k8s](https://github.com/elastic/cloud-on-k8s/) operator.
basic auth is now mandatory (its x-pack)

from experimentation i found that kibana_user works, but remote_monitoring_collector will not.
but i'm not sure what the minimal set is.

**Comment by lukas-vlcek** [comment]
You need to use (or create a new) role that can access `cluster:monitor/prometheus/metrics` resource.

This is the relevant line in the source code of this plugin where the resource is named:
https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/master/src/main/java/org/elasticsearch/action/NodePrometheusMetricsAction.java#L26

When used with SearchGuard you can define the following:
```yaml
sg_role_prometheus_perm:
  cluster:
    - cluster:monitor/prometheus/metrics
```

I haven't been testing this with XPack but it should work. Feel free to open a ticket if it does not.

**Comment by tonymadbrain** [comment]
Minimal role for x-pack will be like:
```Json
  "prometheus_metrics_read": {
    "config": {
      "cluster": [
        "cluster:monitor/prometheus/metrics",
        "cluster:monitor/health",
        "cluster:monitor/nodes/stats",
        "cluster:monitor/state"
      ],
      "indices": [
        {
          "names": [
            "*"
          ],
          "privileges": [
            "indices:monitor/stats"
          ]
        }
      ]
    }
  }
```

**Comment by lukas-vlcek** [comment]
@tonymadbrain I would expect that cluster role `cluster:monitor/prometheus/metrics` should work with x-pack too.

**Comment by tonymadbrain** [comment]
@lukas-vlcek nope, this is not enough, I just tested with 7.5.2

**Comment by lukas-vlcek** [comment]
Good to know. We shall add integration test that includes x-pack to automatically cover this integration use case.

**Comment by kishoresaha-gain** [comment]
Just an info. Looks like one extra permission is needed now "cluster:monitor/nodes/info"

`# Allows prometheus users to get the metrics
prometheus:
  reserved: false
  cluster_permissions:
    - "cluster:monitor/health"
    - "cluster:monitor/nodes/stats"
    - "cluster:monitor/state"
    - "cluster:monitor/nodes/info"
    - "cluster:monitor/prometheus/metrics"
  index_permissions:
    - index_patterns:
        - '*'
      allowed_actions:
        - 'indices:monitor/stats'`

**Comment by runderwo** [comment]
I found that several more index permissions were required (terraform format follows):
`privileges: [ 'indices:admin/aliases/get', 'indices:admin/mappings/get', 'indices:monitor/stats', 'indices:data/read/search' ]`

Also, don't call your custom role `monitoring_user` or you may inadvertently (and silently!) overload a built-in anonymous role causing a big headache.
