### ISSUE TITLE
Release for ES 7.4.0.

### ISSUE THREAD

**Issue by lukas-vlcek** [vvanholl/elasticsearch-prometheus-exporter#222]
Release notes: https://www.elastic.co/guide/en/elasticsearch/reference/7.4/release-notes-7.4.0.html

**Comment by lukas-vlcek** [comment]
@vvanholl notice Elasticsearch v7.4.0 requires Gradle 5.6.2+

**Comment by vvanholl** [comment]
@lukas-vlcek This is not the only point.

There are many breaking changes I noticed last days like this commit
https://github.com/elastic/elasticsearch/commit/7895dc9915422a33bb6814ec420c3b068aef4410#diff-5a9a7882cd6a84c92df9fe0e112f6808

For the moment I don't know how to deal with that and I probably need some help.

**Comment by lukas-vlcek** [comment]
Yes, there are breaking changes. I was looking at this today. I think I can nail it soon.

**Comment by fpytloun** [comment]
Hello, do you have any update regarding support for ES 7.4.0?

**Comment by lukas-vlcek** [comment]
I will get to this this week. Thanks for patience.

**Comment by agaengel** [comment]
Hi @lukas-vlcek,

any news about the update?

Regards
Alex

**Comment by lukas-vlcek** [comment]
Sorry for the delay. I was quite busy lately. I know there are users waiting for it. I am getting to it.

**Comment by xtermi2** [comment]
any progress here?

**Comment by lukas-vlcek** [comment]
I will be pushing PR today, stay tuned. There were some changes and I would like to give it some time for testing before we really cut a new release.

**Comment by fpytloun** [comment]
@lukas-vlcek Thank you :-) Are you also going to release version for latest 7.4 version? (7.4.2)

**Comment by lukas-vlcek** [comment]
@fpytloun Yes I am going to prepare PRs. Working on it now. Actually, I am running into some issues with gradle versions when building 7.4.1 and 7.4.2 so we may need to build and prepare new image versions here https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/master/.gitlab-ci.yml#L1 first.

Keep an eye on https://github.com/vvanholl/elasticsearch-prometheus-exporter/issues/226 and https://github.com/vvanholl/elasticsearch-prometheus-exporter/issues/229
