### ISSUE TITLE
Release for ES 7.5.0

### ISSUE THREAD

**Issue by agaengel** [vvanholl/elasticsearch-prometheus-exporter#234]
Release notes: https://www.elastic.co/guide/en/elasticsearch/reference/7.5/release-notes-7.5.0.html

**Comment by jamshid** [comment]
Do you want a separate issue for 7.5.1? 
https://www.elastic.co/guide/en/elasticsearch/reference/7.5/release-notes-7.5.1.html
IDK but if it helps seems fine to skip old point releases and aim to support latest minor release, since Elastic pushes out versions so quickly.

**Comment by lukas-vlcek** [comment]
Started looking at this; let's keep reference to this issue for now: https://github.com/elastic/elasticsearch/issues/49787
