### ISSUE TITLE
Monitoring data is not accurate

### ISSUE THREAD

**Issue by yjiu1990** [vvanholl/elasticsearch-prometheus-exporter#237]
The CPU memory data in the server cannot correspond to the data called by the plug-in. Could you please tell me how to solve this problem

**Comment by lukas-vlcek** [comment]
Sorry, I do not understand. Can you provide example?

**Comment by yjiu1990** [comment]
![image](https://user-images.githubusercontent.com/41354304/71565691-49fa2480-2aec-11ea-80e9-1b285974289c.png)
For example, if a machine has 2 gigabytes of memory, its free memory is free + buff/cache(195M+591M=786M), not free(195M), because some of its memory is cached in the buff/cache first

**Comment by lukas-vlcek** [comment]
Is this duplicate of https://github.com/vvanholl/elasticsearch-prometheus-exporter/issues/157 ?

**Comment by yjiu1990** [comment]
Yes，To put this into perspective, I found the source code of Elasticsearch, where the algorithm is total-free=used, which I don't think is reasonable
