### ISSUE TITLE
May I ask if the 7.3.2 plug-in can be used for version 7.4 and 7.5?

### ISSUE THREAD

**Issue by yjiu1990** [vvanholl/elasticsearch-prometheus-exporter#239]

**Comment by lukas-vlcek** [comment]
It can not. ES requires each plugin to be released for specific ES version only.
See `elasticsearch.version` in https://www.elastic.co/guide/en/elasticsearch/plugins/7.4/plugin-authors.html#_plugin_descriptor_file
