### ISSUE TITLE
May I ask when the version 7.4.2 will be released?

### ISSUE THREAD

**Issue by yjiu1990** [vvanholl/elasticsearch-prometheus-exporter#242]
Is there any plan to release the version after 7.3.2?

**Comment by lukas-vlcek** [comment]
Yes, there is [waiting PR for 7.4.0](https://github.com/vvanholl/elasticsearch-prometheus-exporter/pull/241) release. Once this one is merged we can release rest of the 7.4.x and 7.5.x
There were some internal API changes in ES with 7.4.0 so it took longer to prepare the release than usual (and there were also the end year holidays).

**Comment by yjiu1990** [comment]
Look forward to your new release

**Comment by lazyusername** [comment]
@lukas-vlcek thx for great work!

**Comment by lukas-vlcek** [comment]
These releases are now found here: https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases
