### ISSUE TITLE
Document how to read the output value of 'es_cluster_status' metric

### ISSUE THREAD

**Issue by milonjames** [vvanholl/elasticsearch-prometheus-exporter#251]
We are getting an output of the Elasticsearch cluster health metric as a number, with no labels having key 'color'. In this situation, we are trying to understand how this number output maps to the well-known ES color codes which indicate the cluster health. Pasting below how we are getting the metric displayed in '/metrics' endpoint

\###################################
\# HELP es_cluster_status Cluster status
\# TYPE es_cluster_status gauge
es_cluster_status{cluster="dummy-cluster",} 0.0
\###################################

**Comment by lukas-vlcek** [comment]
Yes, it should be documented. This not the first time this question comes up, see https://github.com/vvanholl/elasticsearch-prometheus-exporter/issues/169

Generally, codes translate to names using the following formula: https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/cluster/health/ClusterHealthStatus.java#L30-L32

Closing as this is duplicate of https://github.com/vvanholl/elasticsearch-prometheus-exporter/issues/170

**Comment by milonjames** [comment]
Thankyou @lukas-vlcek , now I know 💐.

**Comment by lukas-vlcek** [comment]
@milonjames PRs are always welcome :-)
