### ISSUE TITLE
Per-index statistics

### ISSUE THREAD

**Issue by jperville** [vvanholl/elasticsearch-prometheus-exporter#26]
Is there a way for this plugin to expose the indices stats (see here https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html )?

I would like to add index-specific panel in my custom Grafana dashboard (based on your sample dashboard) such as "number of document per index".

**Comment by vvanholl** [comment]
Hi @jperville,

This is something I have considered to develop soon and this shouldn't be too difficult too implement.

However I think this should be an optional feature to be switch on in ES configuration file. In fact you have clusters with too many indices, and fetching metrics could painfull.

**Comment by jperville** [comment]
If you have some clues on how to get started I will see what I can do (I am total novice in go).

**Comment by vvanholl** [comment]
You don't need go skills since ElasticSearch plugins are written in java.

**Comment by jperville** [comment]
Sorry, then I have very rusty java skills :)

**Comment by vvanholl** [comment]
@jperville : I am currently working on it as you can see my last commit :)

**Comment by jperville** [comment]
Thank you very much @vvanholl, looking forward to seeing it.

**Comment by abrisse** [comment]
+1

**Comment by ssozonoff** [comment]
Was this ever done ?

**Comment by ssozonoff** [comment]
Hmmm for which version's should this work ? We are running ES 5.6.2 with version 5.6.2.0 of the plugin. Thanks

**Comment by lukas-vlcek** [comment]
If you are using `v5.6.2.0` then I think you should have it, see [5.6.2.0/src/main/java/org/compuscene/metrics/prometheus/PrometheusMetricsCollector.java#L37](https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/5.6.2.0/src/main/java/org/compuscene/metrics/prometheus/PrometheusMetricsCollector.java#L37)
