### ISSUE TITLE
Release 7.6.2

### ISSUE THREAD

**Issue by vvanholl** [vvanholl/elasticsearch-prometheus-exporter#262]
This is a reminder for me and for all contributors, ES 7.6.2 has been released today.

Seeing the changelog (https://www.elastic.co/guide/en/elasticsearch/reference/7.6/release-notes-7.6.2.html), this is mainly a bugfix version.

**Comment by lukas-vlcek** [comment]
Release is available here: https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/tag/7.6.2.0
