### ISSUE TITLE
Incorrect es_os_cpu_percent after upgrade to 7.9.1

### ISSUE THREAD

**Issue by dobegor** [vvanholl/elasticsearch-prometheus-exporter#287]
We've just upgraded elasticsearch cluster and plugin to 7.9.1 and I've noticed that es_os_cpu_percent isn't correct anymore.
Both `top` tool and GKE report the same CPU usage (less than 10%) while the plugin exports unusually high CPU usage (~40%).

I don't know if that's related, but during upgrading ES cluster (we are using ECK) node names remained unchanged, but node IDs did change.

![image](https://user-images.githubusercontent.com/14029650/92398825-ec65af80-f131-11ea-97da-540ea388f4b0.png)

**Comment by dobegor** [comment]
![image](https://user-images.githubusercontent.com/14029650/92399639-4c108a80-f133-11ea-8069-55e3f6c43511.png)
Elasticsearch built-in self-monitoring also reports correct CPU usage.

**Comment by lukas-vlcek** [comment]
@dobegor What formula is used to pull the data for the chart from Prometheus in the first chart?

**Comment by dobegor** [comment]
@lukas-vlcek the default one provided by @vvanholl's dashboard.
`es_os_cpu_percent{cluster="$cluster", node=~"$node"}`
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/14029650/92452944-5b411800-f1c7-11ea-828c-7b2ebfd462c4.png">
GKE metrics:
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/14029650/92453124-8e83a700-f1c7-11ea-9b06-01f87d985e41.png">

**Comment by alantang888** [comment]
I have similar issue, using `7.8.0.0` with elasticsearch 7.8.0. `es_os_cpu_percent` on all data node is always on 100. But I check the node is only using around 35%. And `es_process_cpu_percent` also showing around 35%.

**Comment by lukas-vlcek** [comment]
Actually, I am getting it now too ...

**Comment by lukas-vlcek** [comment]
Ok, I think this is related to cgroup stats, see `os.cgroup` namespace in:
https://www.elastic.co/guide/en/elasticsearch/reference/6.8/cluster-nodes-stats.html

**Comment by dobegor** [comment]
So what does that mean? Why crgroup stats are so different?

**Comment by lukas-vlcek** [comment]
Issue with very similar symptoms was reported in OpenJDK: https://github.com/AdoptOpenJDK/openjdk-support/issues/215
At this point I would recommend anyone hitting this error to check version of JVM they use and make sure it is **11.0.9 or later**.
It seems this can be a result of JVM bug: https://bugs.openjdk.java.net/browse/JDK-8248803

In any case, it you are hitting this error, please report your JVM version too.

On a general level make sure you follow JVM support matrix recommendations by Elastic: https://www.elastic.co/support/matrix#matrix_jvm

**Comment by doubleknd26** [comment]
I also have same issue with ES v7.15.1, which use jdk 17. Is there anyone who solved this issue?

**Comment by tianshuang** [comment]
@dobegor Is the JVM running in a docker container? Might be related to this bug: [JDK-8265836](https://bugs.openjdk.org/browse/JDK-8265836).

**Comment by dobegor** [comment]
@tianshuang yes it was running in a docker container (using ECK operator). I'm no longer maintaining the setup so I can neither confirm or deny if upgrading JDK fixes the issue.

**Comment by tianshuang** [comment]
I had a similar problem and it was fixed after upgrading JDK minor version to fix version.
