### ISSUE TITLE
GitLab is not longer used, update README.md

### ISSUE THREAD

**Issue by lukas-vlcek** [vvanholl/elasticsearch-prometheus-exporter#309]
The part of https://github.com/vvanholl/elasticsearch-prometheus-exporter#testing mentioning GitLab needs update.

**Comment by vvanholl** [comment]
This has been fixed in https://github.com/vvanholl/elasticsearch-prometheus-exporter/commit/b37f97e03f8f2cf4c31e5292effcc25ba4934e01 commit
