### ISSUE TITLE
Support for ElasticSearch 1.7.1

### ISSUE THREAD

**Issue by karthimohan** [vvanholl/elasticsearch-prometheus-exporter#31]
Hi,
I know we are using a very old version of ElasticSearch. But have some difficulties in migrating the schemas to the new version. We use Prometheus for monitoring and Alerting for all of our system expect ElasticSearch. is there a way i can use this plugin with the ES version 1.7.1? 
Thank you

**Comment by vicfl** [comment]
same here!

**Comment by peimanja** [comment]
+1 support for 1.7.x versions are appreciated

**Comment by vvanholl** [comment]
Hi,
This is a lot work supporting ES 5.x and 2.x branches on my spare time. Unfortunately I have not enough time for another branch. I am sorry for that, but any PR could be welcomed :)
