### ISSUE TITLE
unable to disable indices metrics 

### ISSUE THREAD

**Issue by itskannanraj** [vvanholl/elasticsearch-prometheus-exporter#313]
I tried disabling the index metrics as described by sending a PUT request to /_cluster/settings with this payload. elasticsearch version is 7.13.2

> curl -XPUT -H 'Content-Type: application/json' -k https://hostname:9200/_cluster/settings?pretty -d'{"transient":{"prometheus.indices":false}}'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "transient setting [prometheus.indices], not recognized"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "transient setting [prometheus.indices], not recognized"
  },
  "status" : 400
}

**Comment by lukas-vlcek** [comment]
FYI, there is an integration test to verify this call works:
https://github.com/vvanholl/elasticsearch-prometheus-exporter/blob/ff86a4404fb6fb33da54ecc52911ec9e041dffc3/src/test/resources/rest-api-spec/test/resthandler/20_11_index_level_metrics_disabled.yml#L58

Tests must pass before every release. I did not check your example but was it typo or something like that?
