### ISSUE TITLE
Version bump to v7.16.2

### ISSUE THREAD

**Issue by Eanveden** [vvanholl/elasticsearch-prometheus-exporter#331]
https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-7.16.2.html

Need version bump in order build custom Elasticsearch image

Edit:
Open PR: https://github.com/vvanholl/elasticsearch-prometheus-exporter/pull/329
Created a fork with a new release in case anyone needs asap
https://github.com/Eanveden/elasticsearch-prometheus-exporter

**Comment by jeroenhartgers** [comment]
https://github.com/vvanholl/elasticsearch-prometheus-exporter/pull/329
