### ISSUE TITLE
Elasticsearch 7.17.7 version released

### ISSUE THREAD

**Issue by psychonaut** [vvanholl/elasticsearch-prometheus-exporter#349]
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/release-notes-7.17.7.html

Release the plugin for this version, please.

**Comment by gdubicki** [comment]
Seems to be fixed by https://github.com/vvanholl/elasticsearch-prometheus-exporter/commit/e8b822b2cfdd93789889c89809d4ac1f5080a7aa.

**Comment by psychonaut** [comment]
Version up to date.
