### ISSUE TITLE
per-index metrics on deleted index

### ISSUE THREAD

**Issue by jperville** [vvanholl/elasticsearch-prometheus-exporter#36]
# Bug description

Per-index statistics continue to output per-index metrics for an index after that index has been deleted.

# Scenario

1. Create an index
2. Render /_prometheus/metrics, grep for the index name (the index should be listed in per-index metrics such as `index_doc_number`)
3. Delete the index
4. Verify that the deleted index is not listed anymore in the output of `/_stats`
5. Render /_prometheus/metrics again, the index name is still there.

# Workaround

Restart the elasticsearch process.

# Explanation

I believe that there is some memoization effect at work: The loop in the [updatePerIndexMetrics](https://github.com/AndreaGiardini/elasticsearch-prometheus-exporter/blob/master/src/main/java/org/compuscene/metrics/prometheus/PrometheusMetricsCollector.java#L637-L752) method iterates on the current indexes to update each per-index metric, but there is no code to remove existing metrics about an index which was not listed by `isr.getIndices().entrySet()`.

**Comment by jperville** [comment]
You'll find attached a screenshot demonstrating the issue : 
![elasticsearch-prometheus-phantom-indexes](https://user-images.githubusercontent.com/834791/35735854-65abc91c-0826-11e8-84a7-8f097a4fe5a8.png)

On the screenshot, around 13h39 the number of documents falls to zero (as expected after deleting all the indices) yet the per-index counters remain at their old (larger than zero) value. I would have expected the per-index counters to not be present after the indices have been deleted.

**Comment by abrisse** [comment]
:+1:

**Comment by stobias123** [comment]
bump

**Comment by jperville** [comment]
@lukas-vlcek at the time I opened this issue (may 2017) I was using Elasticsearch v5.3.1 with version 5.3.1.0 of this plugin.
