### ISSUE TITLE
per-index metrics use the "total" stats instead of the "primaries" stats

### ISSUE THREAD

**Issue by jperville** [vvanholl/elasticsearch-prometheus-exporter#37]
# Description

In the output of elasticsearch `/_stat` route, the per-index metrics are grouped either by "total" or by "primaries". The current code seems to be using the "total" variant while I am expecting to use the "primaries" variant.

# Possible solutions

Either:
 - use the "primaries" variant instead of the "total" variant for all per-index metrics
 - export both "primaries" and "total" metrics with the variant stored in a special label

# Example

For example, the `index_doc_number` metric for an index is found in the "total/docs/count" of the index in the output of the `/$INDEX/_stats` route.

Sample document counts:
```sh
$ curl -s 10.130.0.66:9200/_cat/indices/myapp.fr.assets
green open myapp.fr.assets VJpAJyC2TZybRMkipMG58w 3 2 322587 6657 2.7gb 943.5mb

$ curl -s 10.130.0.66:9200/myapp.fr.assets/_stats | jq . | grep -C3 '"docs"'
  },
  "_all": {
    "primaries": {
      "docs": {
        "count": 322587,
        "deleted": 6657
      },
--
      }
    },
    "total": {
      "docs": {
        "count": 967761,
        "deleted": 12157
      },
--
  "indices": {
    "myapp.fr.assets": {
      "primaries": {
        "docs": {
          "count": 322587,
          "deleted": 6657
        },
--
        }
      },
      "total": {
        "docs": {
          "count": 967761,
          "deleted": 12157
        },

$ curl -s 10.130.0.66:9200/_prometheus/metrics | grep index_doc_number.*wisdom.rtlbelgium.fr.assets
es_index_doc_number{cluster="elasticsearch",node="elasticsearch-0",index="myapp.fr.assets",} 967761.0
```

In the above outputs, the current value of the `es_index_doc_number` metric is 967761.0. That value is the same as the one in the "total/docs/count" field. I would expect to see 322587, which is the value of the "primaries/docs/count" field and also the value listed "for humans" by the `/cat/indices` route.

**Comment by abrisse** [comment]
+1

**Comment by jperville** [comment]
@vvanholl could you have a look at this issue? It is important for us and I suspect not too difficult to implement.

**Comment by vvanholl** [comment]
@jperville , This has been corrected in the latest release. Now for per index metrics you have a new label called "context" for switching between total and primaries

**Comment by jperville** [comment]
Hello @vvanholl, I have tested the new feature (after compiling the plugin myself for ES v5.3.1). Would you like me to write a PR explaining how to contribute to the plugin (especially compilation instructions)?
