### ISSUE TITLE
5.4.3.0 Plugin archive contains wrong plugin descriptor

### ISSUE THREAD

**Issue by cgoeller** [vvanholl/elasticsearch-prometheus-exporter#46]
The 5.4.3.0 Archive (https://distfiles.compuscene.net/elasticsearch/elasticsearch-prometheus-exporter-5.4.3.0.zip)  contains the plugin descriptor for version 5.4.2.0.

It's not possible to install it 

```
-> Downloading https://distfiles.compuscene.net/elasticsearch/elasticsearch-prometheus-exporter-5.4.3.0.zip
[=================================================] 100%?? 
Exception in thread "main" java.lang.IllegalArgumentException: plugin [prometheus-exporter] is incompatible with version [5.4.3]; was designed for version [5.4.2]
```

**Comment by vvanholl** [comment]
Hello,

Sorry for the inconvenience, it's solved now :) In fact Gradle did not update as I expected the plugin descriptor.

Vincent
