### ISSUE TITLE
thread context handling is buggy 

### ISSUE THREAD

**Issue by floragunncom** [vvanholl/elasticsearch-prometheus-exporter#57]
You may not want to use the "client" reference, you got on the first call, use for all other calls.
In other words: The "client" must not be stored in an instance variable because its context aware per rest call.
<pre>
//5.x
collector.compareAndSet(null, new PrometheusMetricsCollector(settings, client));

//2.x
if (collector == null)
collector = new PrometheusMetricsCollector(client);
</pre>

See https://groups.google.com/forum/#!topic/search-guard/6iGwoBQ_W0A

**Comment by lukas-vlcek** [comment]
Has this been solved for 5.x and 6.x ?
My PR (#64) solved this for 2.x only for now.
