### ISSUE TITLE
Support for ES >2.4.1

### ISSUE THREAD

**Issue by esseti** [vvanholl/elasticsearch-prometheus-exporter#60]
Hi all, 
I'm running 2.4.4 and the plugin does not work for that version. 
Any plan to update the compatibility?

**Comment by lukas-vlcek** [comment]
There are actually releases for ES 2.4.4.0 and newer. Check https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases
I think the README file in `master` branch is not updated, but in the [`2.x` branch](https://github.com/vvanholl/elasticsearch-prometheus-exporter/tree/2.x) the README file seem to be more up-to-date.

**Comment by vchan2002** [comment]
Given that... will there be support for 2.4.6?  There does not appear to be a release for this...
