### ISSUE TITLE
What is the build schedule for this exporter?

### ISSUE THREAD

**Issue by mstein-agile** [vvanholl/elasticsearch-prometheus-exporter#62]
I am hoping to use this with the new ES 5.6.3 release and was curious whether this gets auto-built with new releases.

**Comment by davidkarlsen** [comment]
It's manual - and there is already a PR for it: https://github.com/vvanholl/elasticsearch-prometheus-exporter/pull/61

**Comment by vvanholl** [comment]
Version 5.6.3.0 has been released today
