### ISSUE TITLE
Why using node name instead of node ID for label?

### ISSUE THREAD

**Issue by lukas-vlcek** [vvanholl/elasticsearch-prometheus-exporter#63]
_I have a question and I did not find any link to community forum, hence creating a ticket._

My question: Why is this plugin using **node name** instead of unique **node ID** for metric label?
Relevant code can be found in `PrometheusMetricsCollector` ctor:

````
node = nodesStatsResponse.getNodes().get(0).getNode().getName();
````

Theoretically, nodes in ES cluster can be given the same name while they are physically different nodes (but they always have different and very unique node id generated by Elasticsearch itself).

I can understand that it makes it more easy to filter the metrics later when querying the data but this comes with risk. Should the node id be actually included into metric label as well? It can be pulled from NodeStat object like this:

````
nodeId =  nodesStatsResponse.getNodes().get(0).getNode().getId();
````

**Comment by davidkarlsen** [comment]
why not add both as labels?

**Comment by lukas-vlcek** [comment]
@davidkarlsen Yes, I think that is correct solution.
I will submit PR for this (actually, it will be part of my other PR that is going to fix #57 and #58).

**Comment by vvanholl** [comment]
In fact, I prefer also having this information as a label instead of replacing node name by ID

**Comment by lukas-vlcek** [comment]
Sure, that is what I meant by saying:

> Should the node id be actually included into metric label as well?

I will include both, the node id and the node name in labels.

**Comment by lukas-vlcek** [comment]
Has this been solved for 5.x and 6.x ?
My PR (#64) solved this for 2.x only for now.
