### ISSUE TITLE
Support Elasticsearch 6.1

### ISSUE THREAD

**Issue by piotrkochan** [vvanholl/elasticsearch-prometheus-exporter#76]
https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-6.1.0.html

**Comment by vvanholl** [comment]
Version 6.1.0.0 has been released

**Comment by thuandt** [comment]
@vvanholl how about 6.1.1 https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-6.1.1.html ?
