### ISSUE TITLE
URL for Grafana dashboard source code?

### ISSUE THREAD

**Issue by lukas-vlcek** [vvanholl/elasticsearch-prometheus-exporter#93]
There is a Grafana dashboard associated to this plugin: <https://grafana.com/dashboards/266>
Is there any URL/GitHub link or anything where I could find the source code?

I am missing some metrics in the dashboard and I would love to contribute back.

**Comment by vvanholl** [comment]
I am sorry but there's no git repo behind. But you have access to the (ugly) json code by clicking on "Download JSON" on the page.

Vincent

**Comment by lukas-vlcek** [comment]
Yes, I downloaded it and I am experimenting with it. I am sure I will need some additional charts there (for example I am missing queues stats, rejected bulk requests and the like...).

**Comment by lukas-vlcek** [comment]
@kedare By the latest version you mean ES 6 or higher?

FYI, I started (re)building dashboard for Grafana here <https://github.com/lukas-vlcek/elasticsearch-mixin/blob/master/dashboards/elasticsearch.libsonnet> but this is highly WIP ATM. There will be a way how to get just the needed JSON (for those who need _just the dashboard_). I plan to add some missing charts into the dashboard too. And of course I plan to make it clear what license this dashboard is using (currently it is very unclear when you install any dashboard directly from <https://grafana.com/dashboards>).

The nice thing is that using _jsonnet_ and related _mixin_ code it will be possible to make the dashboard parametrized and allow for custom names of Prometheus metrics. I will definitely update this thread when I have more news to share.

**Comment by himmatb** [comment]
Can i get indices size based on per indices in grafana dashboards .. are we capturing this kind of metrix in this plugin/ Dashboard ? 

Please help me to this kind of requirement .. Please help me on this..

**Comment by lukas-vlcek** [comment]
@himmatb Yes, you can.

You can use Prometheus queries like:
```
topk(
  10, max(
    es_index_store_size_bytes{cluster="$cluster", node=~"$node", context="primaries"}
  )
by (index))
```

to get top 10 largest indices for example.

I am trying to add this type of information into dashboard as well (currently in [indices_table](https://github.com/lukas-vlcek/elasticsearch-mixin/blob/d7b03a4d91d4bcd7543a795939cb0b094ef6ad24/dashboards/elasticsearch.libsonnet#L426) branch). But I am struggling with Grafana tables as the moment. I need more time to get it working right.

**Comment by kedare** [comment]
Both ES6 and the last version of the exporter, the metrics names changed apparently

**Comment by praveenmak** [comment]
Hi @lukas-vlcek 

Do you have a dashboard update? I am having problems too. Please let me know.
