### ISSUE TITLE
Elasticsearch version 2.4.4 compatibility

### ISSUE THREAD

**Issue by imanandshah** [vvanholl/elasticsearch-prometheus-exporter#97]
I need to use for Elasticsearch version 2.4.4 and it fails. Can you help? 

Verifying https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/2.4.1.0/elasticsearch-prometheus-exporter-2.4.1.0.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Plugin [prometheus-exporter] is incompatible with Elasticsearch [2.4.4]. Was designed for version [2.4.1]

Do we have something as a workaround?

**Comment by himmatb** [comment]
Just use other branch which is tagged with 2.4.4.0 .. 
https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/2.4.4.0/elasticsearch-prometheus-exporter-2.4.4.0.zip
