### ISSUE TITLE
Request: Determine if index is read only

### ISSUE THREAD

**Issue by pjhampton** [vvanholl/elasticsearch-prometheus-exporter#98]
Hey - great plugin! Friendly request,

We have an ES cluster under serious stress at work and there has been a couple of occasions a file system on the vm when the nodes persistence goes above 95% and the index goes read only. It would be great if there was a metric for this.

We have resorted (rightfully) to monitoring this at a box level, but would be great if we could catch it here too.

**Comment by pjhampton** [comment]
We found we can tell this from the circuit breakers tripping! Thanks any :+1:

**Comment by benjaminjb** [comment]
Oh, thanks for this, but just out of curiosity, would a count of read_only_indices be a pain to implement?

**Comment by lukas-vlcek** [comment]
for the record see #230
